/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class no_shhsoft_camcapture_JniAdapter */

#ifndef _Included_no_shhsoft_camcapture_JniAdapter
#define _Included_no_shhsoft_camcapture_JniAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     no_shhsoft_camcapture_JniAdapter
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_no_shhsoft_camcapture_JniAdapter_init
  (JNIEnv *, jobject);

/*
 * Class:     no_shhsoft_camcapture_JniAdapter
 * Method:    getDefaultDevice
 * Signature: ()Lno/shhsoft/camcapture/CamCaptureDevice;
 */
JNIEXPORT jobject JNICALL Java_no_shhsoft_camcapture_JniAdapter_getDefaultDevice
  (JNIEnv *, jobject);

/*
 * Class:     no_shhsoft_camcapture_JniAdapter
 * Method:    free
 * Signature: (Lno/shhsoft/camcapture/CamCaptureDevice;)V
 */
JNIEXPORT void JNICALL Java_no_shhsoft_camcapture_JniAdapter_free
  (JNIEnv *, jobject, jobject);

/*
 * Class:     no_shhsoft_camcapture_JniAdapter
 * Method:    setResolutionIndex
 * Signature: (Lno/shhsoft/camcapture/CamCaptureDevice;I)V
 */
JNIEXPORT void JNICALL Java_no_shhsoft_camcapture_JniAdapter_setResolutionIndex
  (JNIEnv *, jobject, jobject, jint);

/*
 * Class:     no_shhsoft_camcapture_JniAdapter
 * Method:    getResolutionIndex
 * Signature: (Lno/shhsoft/camcapture/CamCaptureDevice;)I
 */
JNIEXPORT jint JNICALL Java_no_shhsoft_camcapture_JniAdapter_getResolutionIndex
  (JNIEnv *, jobject, jobject);

/*
 * Class:     no_shhsoft_camcapture_JniAdapter
 * Method:    open
 * Signature: (Lno/shhsoft/camcapture/CamCaptureDevice;)V
 */
JNIEXPORT void JNICALL Java_no_shhsoft_camcapture_JniAdapter_open
  (JNIEnv *, jobject, jobject);

/*
 * Class:     no_shhsoft_camcapture_JniAdapter
 * Method:    close
 * Signature: (Lno/shhsoft/camcapture/CamCaptureDevice;)V
 */
JNIEXPORT void JNICALL Java_no_shhsoft_camcapture_JniAdapter_close
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
